name: Build Solution

on: [push]

jobs:
  build:
    runs-on: windows-latest # or ubuntu-latest if using dotnet core and compatible libraries

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Specify your required version

    - name: Restore dependencies
      run: dotnet restore your-solution-name.sln

    - name: Build the project
      run: dotnet build your-solution-name.sln --no-restore --configuration Release
