name: MSBuild

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore usermode/cormem_test.sln

    - name: Build solution
      run: msbuild usermode/cormem_test.sln /p:Configuration=Release /p:Platform=x64
